### ISSUE TITLE
http_method.cpp won't compile with GCC 10.1.0

### ISSUE THREAD

**Issue by sandman7920** [expresscpp/expresscpp#5]
GCC 10.1.0 can't compile `http_method.cpp`.

```C++
/usr/include/boost/utility/ostream_string.hpp: In instantiation of ‘std::basic_ostream<charT, traits>& boost::ostream_string(std::basic_ostream<charT, traits>&, const charT*, std::size_t) [with charT = char; traits = std::char_traits<char>; std::size_t = long unsigned int]’:
/usr/include/boost/utility/string_view.hpp:581:37:   required from ‘std::basic_ostream<charT, traits>& boost::operator<<(std::basic_ostream<charT, traits>&, const boost::basic_string_view<charT, traits>&) [with charT = char; traits = std::char_traits<char>]’
/usr/include/boost/beast/http/verb.hpp:150:29:   required from here
/usr/include/boost/utility/ostream_string.hpp:71:29: error: invalid use of incomplete type ‘class std::basic_ostream<char>’
   71 |     typename stream::sentry entry(os);
```

Adding `#include <ostream>` resolve the issue

P.S.
I don't known if this is a boost_beast problem.

**Comment by gocarlos** [comment]
yes, seems related to this: https://lists.boost.org/boost-users/2020/05/90421.php

**Comment by gocarlos** [comment]
it seems like boost beast 1.73 has still issues with gcc 10 and c++20 mode, just lowered the default cpp standard to cpp17 -> works on my side now
